apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-inc5
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-777-0081-tenant/ci10t-777-0081-app/devfile-sample-inc5@sha256:042886a9dfd7ccf3b71c48127cbb37dc4cf02c49577dd77c6af01a33e6003e0b
        name: my-nodejs
        resources: {}
status: {}
