apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-inc5
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-inc5
    app.kubernetes.io/part-of: ci10t-777-0081-app
  name: devfile-sample-inc5
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-inc5
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-inc5
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-777-0081-tenant/ci10t-777-0081-app/devfile-sample-inc5@sha256:042886a9dfd7ccf3b71c48127cbb37dc4cf02c49577dd77c6af01a33e6003e0b
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
